   - domain_uuid: 9412a720-dc9f-11e6-9909-05c2baf48116
     files:
       - document_id: "1"
         format: "application/pdf"
         description: "CoderBot - Guida per l'assemblaggio"
         tags:
           - "guida"
           - "assemblaggio"
         i18n:
           - language: "it"
             url: "https://drive.google.com/file/d/0B1izPlSjqvFyRVhOcWltcmUzSHc/view?usp=sharing"
             description: "CoderBot - Guida per il montaggio"
             created_at: 2017-03-17 12:00:00
             updated_at: 2017-03-17 12:00:00
